id: D48E0224A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T09:24:26+00:00'
last_modified: '2022-05-27T10:03:47.784818+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    dfa0:
      image_group_id: I1PD95907
      title: དབུ་མའི་རྒྱན་གྱི་དཀའ་འགྲེལ།
      total_pages: 1557
      order: 62
      base_file: dfa0.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
