id: 73afe7f4e2d34350a308b02f9d443698
initial_creation_type: ocr
source_metadata:
  volumes:
    10fbb5965ecf44a3a755cff1e3298986:
      base_file: v061.txt
      image_group_id: I1PD95907
      title: ''
      total_pages: 1557
      volume_number: 62
